trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: PowerShell@2
  inputs:
    filePath: './restore.ps1'
    pwsh: true

- task: PowerShell@2
  inputs:
    filePath: './run-tests.ps1'
    pwsh: true