trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: .\restore.ps1
  displayName: 'Restore dependencies'

- task: Pester@8
  inputs:
    scriptFolder: '$(System.DefaultWorkingDirectory)\*'
    resultsFile: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
    run32Bit: False