trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: PowerShell@2
  inputs:
    filePath: '.\restore.ps1'

- task: Pester@8
  inputs:
    scriptFolder: '$(System.DefaultWorkingDirectory)\*'
    resultsFile: '$(System.DefaultWorkingDirectory)\Test-Pester.XML'
    run32Bit: False